---
- name: Generate config-file
  template:
    src: "script_config.cfg.j2"
    dest: "/home/{{ item.name }}/etc/script_config.cfg"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Create lib/shell-functions-directory
  file:
    path: "/home/{{ item.name }}/lib/shell-functions"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Copy storage_operations.functions
  copy:
    src: "storage_operations.functions"
    dest: "/home/{{ item.name }}/lib/shell-functions/storage_operations.functions"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Copy picture_admin.sh
  copy:
    src: "picture_admin.sh"
    dest: "/home/{{ item.name }}/bin/picture_admin.sh"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0744'
  become: yes
  with_items:
    - "{{ admin_users }}"
  when:
    - "'image_admin' in item.script_pkg"
    - "scripts is defined"
    - "'image_admin' in scripts"

- name: Copy convert_webp.sh
  copy:
    src: "convert_webp.sh"
    dest: "/home/{{ item.name }}/bin/convert_webp.sh"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0744'
  become: yes
  with_items:
    - "{{ admin_users }}"
  when:
    - "'image_admin' in item.script_pkg"
    - "scripts is defined"
    - "'image_admin' in scripts"
